#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : plasma-integration
Version  : 5.13.4
Release  : 2
URL      : https://download.kde.org/stable/plasma/5.13.4/plasma-integration-5.13.4.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.13.4/plasma-integration-5.13.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: plasma-integration-lib
Requires: plasma-integration-license
Requires: plasma-integration-data
Requires: plasma-integration-locales
BuildRequires : breeze-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kwayland-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : qtbase-dev qtbase-extras mesa-dev
BuildRequires : qtx11extras-dev

%description
# Framework Integration
Integration of Qt application with KDE workspaces
## Introduction

%package data
Summary: data components for the plasma-integration package.
Group: Data

%description data
data components for the plasma-integration package.


%package lib
Summary: lib components for the plasma-integration package.
Group: Libraries
Requires: plasma-integration-data
Requires: plasma-integration-license

%description lib
lib components for the plasma-integration package.


%package license
Summary: license components for the plasma-integration package.
Group: Default

%description license
license components for the plasma-integration package.


%package locales
Summary: locales components for the plasma-integration package.
Group: Default

%description locales
locales components for the plasma-integration package.


%prep
%setup -q -n plasma-integration-5.13.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535774720
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535774720
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/plasma-integration
cp COPYING.LGPL-3 %{buildroot}/usr/share/doc/plasma-integration/COPYING.LGPL-3
pushd clr-build
%make_install
popd
%find_lang plasmaintegration5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kconf_update/fonts_akregator.pl
/usr/share/kconf_update/fonts_akregator.upd
/usr/share/kconf_update/fonts_global.pl
/usr/share/kconf_update/fonts_global.upd
/usr/share/kconf_update/fonts_global_toolbar.upd
/usr/share/kconf_update/fonts_kate.pl
/usr/share/kconf_update/fonts_kate.upd

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/platformthemes/KDEPlasmaPlatformTheme.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/plasma-integration/COPYING.LGPL-3

%files locales -f plasmaintegration5.lang
%defattr(-,root,root,-)

